name: CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master         # Push events on master branch
      - 'releases/*'   # Push events to branches matching refs/heads/releases/*

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Build self-contained for windows, linux and osx
      run: |
        cd GhostToGitHubPagesConverter
        dotnet publish --configuration Release /p:PublishSingleFile=true --runtime win-x64
        dotnet publish --configuration Release /p:PublishSingleFile=true --runtime linux-x64
        dotnet publish --configuration Release /p:PublishSingleFile=true --runtime osx-x64
