name: CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master         # Push events on master branch
      - 'releases/*'   # Push events to branches matching refs/heads/releases/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [win-x64, linux-x64, osx-x64]
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build self-contained for ${{ matrix.runtime }}
      run: |
        cd GhostToGitHubPagesConverter
        dotnet publish --configuration Release /p:PublishSingleFile=true --runtime ${{ matrix.runtime }}
